language: ruby
before_install:
  - gem install bundler
rvm:
  - 2.3.1

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

# uncomment this line if your project needs to run something other than `rake`:
addons:
    code_climate:
        repo_token: 9ced3e3fc9125925f7bf5a6938011dc79278251741efacc02a48a5265af2416e
script: bundle exec rake test
